INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (1, N'Фен')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (2, N'Пылесос')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (3, N'Телевизор')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (4, N'Стиральная машина')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (5, N'Микроволновка')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (6, N'Утюг')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (7, N'Миксер')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (8, N'Кофемашина')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (9, N'Посудомоечная машина')
INSERT INTO [dbo].[Product] ([Id], [Name]) VALUES (10, N'Плита электрическая')
